# Generated by Django 5.0.2 on 2024-04-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
