# Generated by Django 5.0.2 on 2024-04-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0002_leave_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="leave_duration",
            field=models.CharField(
                choices=[
                    ("Singleday", "Singleday"),
                    ("Multipledays", "Multipledays"),
                    ("Hours", "Hours"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
