# Generated by Django 5.0.2 on 2024-02-27 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cms", "0035_auto_20230822_2208"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sevices_Model",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField()),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
