# Generated by Django 5.0.2 on 2024-03-14 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="department",
        ),
        migrations.AddField(
            model_name="appointment",
            name="availble",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="on_leave",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
