# Generated by Django 5.0.2 on 2024-03-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_appointment_department_appointment_availble_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sevices_model",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="static/img"),
        ),
    ]
