# Generated by Django 5.0.2 on 2024-03-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_sevices_model_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sevices_model",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="img"),
        ),
    ]
