# Generated by Django 5.0.2 on 2024-04-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_sevices_model_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="on_leave",
            new_name="available",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="availble",
        ),
        migrations.AddField(
            model_name="doctor",
            name="appointment_duration",
            field=models.CharField(
                choices=[
                    ("MINUTES_15", "15 minutes"),
                    ("MINUTES_30", "30 minutes"),
                    ("MINUTES_45", "45 minutes"),
                    ("HOURS_1", "1 hour"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
