# Generated by Django 5.0.2 on 2024-04-26 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="available",
        ),
        migrations.AddField(
            model_name="doctor",
            name="desciption",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="doctor_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/doctorimage"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="qualification",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="appointment_duration",
            field=models.CharField(
                choices=[
                    ("00:00", "00:00"),
                    ("01:00", "01:00"),
                    ("02:00", "02:00"),
                    ("03:00", "03:00"),
                    ("04:00", "04:00"),
                    ("05:00", "05:00"),
                    ("06:00", "06:00"),
                    ("07:00", "07:00"),
                    ("08:00", "08:00"),
                    ("09:00", "09:00"),
                    ("10:00", "10:00"),
                    ("11:00", "11:00"),
                    ("12:00", "12:00"),
                    ("13:00", "13:00"),
                    ("14:00", "14:00"),
                    ("15:00", "15:00"),
                    ("16:00", "16:00"),
                    ("17:00", "17:00"),
                    ("18:00", "18:00"),
                    ("19:00", "19:00"),
                    ("20:00", "20:00"),
                    ("21:00", "21:00"),
                    ("22:00", "22:00"),
                    ("23:00", "23:00"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="hospital",
            field=models.ManyToManyField(blank=True, to="myapp.hospital"),
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("CasualLeave", "Casual Leave"),
                            ("MedicalLeave", "Medical Leave"),
                            ("PaidLeave", "Paid Leave"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "leave_duration",
                    models.CharField(
                        choices=[
                            ("Singleday", "Singleday"),
                            ("Multipledays", "Multipledays"),
                            ("hours", "hours"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.TimeField()),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.doctor",
                    ),
                ),
            ],
        ),
    ]
