# Generated by Django 5.0.2 on 2024-04-26 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_hospital_remove_doctor_available_doctor_desciption_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
