# Generated by Django 5.0.2 on 2024-04-29 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="desciption",
            new_name="description",
        ),
    ]
