# Generated by Django 5.0.2 on 2024-04-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0003_remove_doctor_email_remove_doctor_name_doctor_doctor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="doctor",
            new_name="user",
        ),
        migrations.AddField(
            model_name="doctor",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
